language: scala

scala:
   - 2.10.4
   #2.12.1 doesn't work on Travis CI which is the version I use on my local machine

jdk:
  - openjdk7

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
  - sbt ++$TRAVIS_SCALA_VERSION test

notifications:
  email:
    recipients:
      - fishercoder@gmail.com
    on_success: always
    on_failure: always