language: scala

scala:
   - 2.10.4

jdk:
  - openjdk7

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt compile
  - sbt package
  - sbt run

notifications:
  email:
    recipients:
      - fishercoder@gmail.com
    on_success: always
    on_failure: always